name: Deploy Flutter Web to GitHub Pages with Peanut

on:
  # Se ejecuta en los pushes a la rama principal
  push:
    branches: ["main"]

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Establece los permisos del GITHUB_TOKEN para permitir el despliegue en GitHub Pages
# Nota: contents:write es necesario para que peanut pueda hacer push a gh-pages
permissions:
  contents: write
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Peanut necesita el historial completo para poder crear/actualizar la rama gh-pages
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.32.5

      - name: Install dependencies
        run: flutter pub get

      - name: Install peanut
        run: flutter pub global activate peanut

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Build and deploy with peanut
        run: |
          echo "Construyendo con peanut - este método evita symlinks automáticamente"
          # Nota: pasamos web-renderer y base-href con --extra-args
          flutter pub global run peanut --extra-args "--web-renderer canvaskit --base-href=/calcular_parte/" --message "Deploy Flutter web app to GitHub Pages"

          echo "Verificando contenido generado por peanut"
          ls -la

          echo "Publicando a gh-pages"
          git push origin gh-pages
